export const GET_SELECT_LOGO = 'GET_SELECT_LOGO';

export const FETCH_REACTID_BEGIN = 'FETCH_REACTID_BEGIN';
export const FETCH_REACTID_SUCCESS = 'FETCH_REACTID_SUCCESS';
export const FETCH_REACTID_FAILURE = 'FETCH_REACTID_FAILURE';

export const FETCH_FORMACION_BEGIN = 'FETCH_FORMACION_BEGIN';
export const FETCH_FORMACION_SUCCESS = 'FETCH_FORMACION_SUCCESS';
export const FETCH_FORMACION_FAILURE = 'FETCH_FORMACION_FAILURE';
